version: '2'

services:
  zookeeper:
  image: confluentinc/cp-zookeeper:latest
  environemt:
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 2000
  ports:
    - 22181:2181
  
  kafka:
    image: confluentinc/cp-zookeeper:5.3.1
    depends_on:
      - zookeeper
    ports:
      - 29092: 29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, 
      PLAINTEXT_HOST: PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTION: 1